# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907b7f07d1e004b2bd338d91c93bf4cad3e686009376833e522de2da73581cbcc805f684f5b8856c74f67d298959d4d855aa5024c69ec6c8b4ace8f75120536f

test:
  secret_key_base: 62f170437097baf669e8048edb59198aba6aa984707ae8076d5d5b925cf5cd2d6c98daa1ccc05f90e5dbe97d886b54f0fbe4342c98fabd592d3799c83191a63f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
